### ISSUE TITLE
AttributeError: _2D

### ISSUE THREAD

**Issue by komilaria** [FeiiYin/StyleHEAT#43]
(StyleHEAT2) C:\Users\USER\Desktop\aria\StyleHEAT-styleheat>python inference.py --config configs/inference.yaml --video_source=./docs/demo/videos/RD_Radio34_003_512.mp4 --image_source=./docs/demo/images/100.jpg --cross_id --if_extract --output_dir=./docs/demo/output
Traceback (most recent call last):
  File "inference.py", line 5, in <module>
    import utils.inference_util as inference_util
  File "C:\Users\USER\Desktop\aria\StyleHEAT-styleheat\utils\inference_util.py", line 10, in <module>
    from data.inference_dataset import TempVideoDataset, ImageDataset
  File "C:\Users\USER\Desktop\aria\StyleHEAT-styleheat\data\inference_dataset.py", line 5, in <module>
    from utils.video_preprocess.extract_landmark import get_landmark
  File "C:\Users\USER\Desktop\aria\StyleHEAT-styleheat\utils\video_preprocess\extract_landmark.py", line 6, in <module>
    detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)
  File "C:\Users\USER\miniconda3\envs\StyleHEAT2\lib\enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

hello dears

who can solve this issue?

**Comment by mcramos68** [comment]
sed -i -e 's/_2D/TWO_D/g' $(find . -name \*.py)

make sure you're in the right directory

**Comment by 1315382539** [comment]
It's possible that the issue is related to the version of face_alignment. I recommend switching to face_alignment version 1.3.2. You can do this by running the following command: ` pip install face_alignment==1.3.2`

**Comment by qianx77** [comment]
this is the problem caused by different version of face_alignment， you can change the function from `face_alignment.LandmarksType._2D` to `face_alignment.LandmarksType.TWO_D`

**Comment by mrbig0** [comment]
> It's possible that the issue is related to the version of face_alignment. I recommend switching to face_alignment version 1.3.2. You can do this by running the following command: ` pip install face_alignment==1.3.2`

Yes that was basically the problem.
